Add new SIUE CC* cluster
opensciencegrid/topology pull request #1734
Opened 2021-04-06 18:41 UTC by lebonez

Adding in the new CC* cluster. It is going to be connected to the same CE. I am unsure if I need to update anything else. The CE is not active yet. Also, canor should we delete the old "SIUE - OS" which is never coming back?

2021-04-06 19:11 UTC, brianhlin requested changes
Hi @lebonez a few requested changes/suggestions. Also, don't worry about removing the old CE. As long as it's marked inactive, we keep it around for accounting reasons.

2021-04-06 19:11 UTC, brianhlin commented on topology/Southern Illinois University Edwardsville/SIUE - CC/SIUE-CC-production.yaml
> +          hidden: false
```suggestion
          hidden: false
    Tags:
      - CC*
```

For CC* resources, we have a special tag for them

2021-04-06 20:56 UTC, lebonez commented on topology/Southern Illinois University Edwardsville/SIUE - CC/site.yml
> +
Change made thanks!

2021-04-06 22:01 UTC, brianhlin commented on topology/Southern Illinois University Edwardsville/SIUE - CC/site.yml
> +
Hey @lebonez it looks like our CI is very picky and requires that the file be named `SITE.yaml` instead of `SITE.yml`. Could you rename it again?

2021-04-07 12:21 UTC, lebonez commented on topology/Southern Illinois University Edwardsville/SIUE - CC/site.yml
> +
Whoops didn't catch that file type. Used to ansible where the convention is yml. Thanks!

2021-04-07 12:44 UTC, lebonez commented on topology/Southern Illinois University Edwardsville/SIUE - CC/site.yml
> +
Alrighty I have fixed the CI errors. I'm assuming the resource name is fine?

2021-04-07 13:03 UTC, lebonez commented on topology/Southern Illinois University Edwardsville/SIUE - CC/site.yml
> +
I think I have everything set correctly now. We should be good to go if every looks good.

2021-04-07 13:46 UTC, brianhlin approved these changes
LGTM now, thanks!

2021-04-07 13:47 UTC, merged