Add New Endpoints ( SOFTWARE-4346 )
opensciencegrid/topology pull request #2368
Opened 2022-03-22 19:12 UTC by CannonLock

Add the new endpoints and some tests to verify

2022-03-24 18:46 UTC, brianhlin reviewed
@matyasselmeci it took me a minute to swap this back in but looking at the endpoints, doesn't it make more sense to have `/<server-type>-<auth-config-type>`? In other words these would stay the same:

- `/cache-authfile`
- `/cache-authfile-public`

And we'd change the following:

- `/scitokens-cache` -> `/cache-scitokens`
- `/scitokens-origin` -> `/origin-scitokens`

2022-03-24 21:18 UTC, matyasselmeci commented
Yes that does look better. Maybe we could even do
```
/cache/Authfile
/cache/Authfile-public
/cache/scitokens.conf
```

2022-03-24 21:22 UTC, brianhlin commented
And `/origin/scitokens.conf`! @CannonLock could you go ahead and make these changes? Otherwise everything else looks reasonable to me

2022-03-24 21:25 UTC, matyasselmeci commented
Right, `/origin/all of those`

2022-03-28 14:43 UTC, CannonLock commented
@matyasselmeci @brianhlin 

To confirm there should be 6 new endpoints:

- /cache/Authfile
- /cache/Authfile-public
- /cache/scitokens.conf
- /origin/Authfile
- /origin/Authfile-public
- /origin/scitokens.conf

2022-03-28 16:46 UTC, CannonLock commented
@matyasselmeci I have applied the changes and tests to accompany.

2022-03-28 17:46 UTC, matyasselmeci requested changes
Mostly just some text that needs to be swapped; otherwise it's fine. See comments.

2022-03-28 17:46 UTC, matyasselmeci commented on src/app.py
> +    cache_fqdn = request.args.get("cache_fqdn") if request.args.get("cache_fqdn") else request.args.get("fqdn")
```suggestion
    cache_fqdn = request.args.get("fqdn") if request.args.get("fqdn") else request.args.get("cache_fqdn")
```

2022-03-28 17:46 UTC, matyasselmeci commented on src/app.py
> +        return Response("FQDN of cache or origin server required in the 'cache_fqdn' or 'origin_fqdn' argument", status=400)
```suggestion
        return Response("FQDN of cache or origin server required in the 'fqdn' argument", status=400)
```

2022-03-28 17:46 UTC, matyasselmeci commented on src/tests/test_api.py
> +            current_endpoint = client.get(f"/stashcache/authfile-public?cache_fqdn={resource_fqdn}")
```suggestion
            current_endpoint = client.get(f"/cache/Authfile-public?fqdn={resource_fqdn}")
            previous_endpoint = client.get(f"/stashcache/authfile-public?cache_fqdn={resource_fqdn}")
```

2022-03-28 17:46 UTC, matyasselmeci commented on src/tests/test_api.py
> +            current_endpoint = client.get(f"/stashcache/origin-authfile?fqdn={resource_fqdn}")
```suggestion
            current_endpoint = client.get(f"/origin/Authfile?fqdn={resource_fqdn}")
            previous_endpoint = client.get(f"/stashcache/origin-authfile?fqdn={resource_fqdn}")
```

2022-03-28 17:46 UTC, matyasselmeci commented on src/tests/test_api.py
> +            current_endpoint = client.get(f"/stashcache/origin-authfile-public?fqdn={resource_fqdn}")
```suggestion
            current_endpoint = client.get(f"/origin/Authfile-public?fqdn={resource_fqdn}")
            previous_endpoint = client.get(f"/stashcache/origin-authfile-public?fqdn={resource_fqdn}")
```

2022-03-28 18:17 UTC, matyasselmeci approved these changes
LGTM.

2022-03-28 18:17 UTC, matyasselmeci commented
You should merge changes from master and then I can merge this PR.

2022-03-28 18:20 UTC, CannonLock commented
@matyasselmeci Done

2022-03-28 18:21 UTC, merged