SOFTWARE-5347
opensciencegrid/topology pull request #2782
Opened 2022-11-29 20:26 UTC by AidenCohen31

2022-12-01 01:59 UTC, brianhlin commented on src/topology_utils.py
> +>>>>>>> master
There's a couple of diff-looking lines that seemed to have snuck in here somehow. Can you clean them up?

2022-12-01 03:04 UTC, AidenCohen31 commented
Oh, that was an accident, I guess I didn't push the merge

On Wed, Nov 30, 2022, 7:59 PM Brian Lin ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/topology_utils.py
> <https://github.com/opensciencegrid/topology/pull/2782#discussion_r1036620108>
> :
>
> >
> +=======
> +    session['cert_reqs'] = 'CERT_REQUIRED'
> +>>>>>>> master
>
> There's a couple of diff-looking lines that seemed to have snuck in here
> somehow. Can you clean them up?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/opensciencegrid/topology/pull/2782#pullrequestreview-1200266510>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI3ZOTNDD3GWE65HR3BTVWLWLABBPANCNFSM6AAAAAASO4LWFQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-13 21:37 UTC, AidenCohen31 commented
Revamped structure, should be good now

2022-12-21 23:39 UTC, brianhlin reviewed
We have a service called the "OSPool" so I'm renaming the class to avoid tricky typos in the future

2022-12-21 23:39 UTC, brianhlin commented on bin/osg-notify
> +from topology_utils import OSGPoolManager
```suggestion
from topology_utils import TopologyPoolManager
```

2022-12-21 23:39 UTC, brianhlin commented on bin/osg-notify
> +    pm = OSGPoolManager()
```suggestion
    pm = TopologyPoolManager()
```

2022-12-21 23:39 UTC, brianhlin commented on bin/osg-notify
> +        results = OSGPoolManager.filter_contacts(args, results)
```suggestion
        results = TopologyPoolManager.filter_contacts(args, results)
```

2022-12-21 23:39 UTC, brianhlin commented on bin/osg-notify
> +        results = OSGPoolManager.filter_contacts(args, results)
```suggestion
        results = TopologyPoolManager.filter_contacts(args, results)
```

2022-12-21 23:39 UTC, brianhlin commented on src/topology_utils.py
> +class OSGPoolManager(urllib3.PoolManager):
```suggestion
class TopologyPoolManager(urllib3.PoolManager):
```

2022-12-22 15:30 UTC, brianhlin requested changes
Hey @AidenCohen31 this looks solid but could you take all the static methods out of the `TopologyPoolManager` class?

As you already know, these methods don't act on a given instance of the class so they don't need to be there and we should be especially conservative when changing an interface of the library. It's anybody's guess who's using these methods from our library and if we change the way they need to invoke the methods, their code may break!

2024-03-08 17:49 UTC, merged