Create Site.yaml
opensciencegrid/topology pull request #2857
Opened 2023-01-05 19:29 UTC by biozit

2023-01-05 19:35 UTC, brianhlin commented
@biozit do you have a relevant ticket? A descriptive PR title + commit and a description would go a long way to helping us understand the PR!

2023-01-06 04:03 UTC, biozit commented
This is the registration of the new I2 OSDF caches, @djw8605 is the PI.

2023-01-06 16:08 UTC, brianhlin requested changes
Some minor changes to the LongName and Descriptions for the sites (we should spell out acronyms in descriptions/long names wherever possible). The CI is complaining about missing `SITE.yaml` so I think that the filenames are case sensitive.

Do you have DNs? We may also have to update the IDs

2023-01-06 16:08 UTC, brianhlin commented on topology/Internet2/Internet2Boise/Site.yaml
> +Description: Backbone location of Internet2 at the Boise POP
```suggestion
LongName: Internet2 Boise
Description: Backbone location of Internet2 at the Boise Point of Presence
```

2023-01-06 16:08 UTC, brianhlin commented on topology/Internet2/Internet2Jacksonville/Site.yaml
> +Description: Backbone location of Internet2 at the Jacksonville POP
```suggestion
LongName: Internet2 Jacksonville
Description: Backbone location of Internet2 at the Jacksonville Point of Presence
```

2023-01-06 16:50 UTC, biozit commented
I requested the cert to I2

2023-01-12 19:59 UTC, biozit commented
@brianhlin could we merge Boise and Cincinnati? these two caches are ready!

2023-01-12 20:03 UTC, brianhlin commented
Hi @biozit this PR has more caches than just Boise and Cincinnati. Can you split those changes off into separate PRs?

2023-01-12 20:16 UTC, biozit commented
https://github.com/opensciencegrid/topology/pull/2880

2023-01-20 20:34 UTC, edquist commented
Hi @biozit, I'm seeing the following error in our checks:
```
Missing site Internet2Jacksonville for RG Site.  Is there a SITE.yaml?
```

2023-01-23 20:10 UTC, biozit commented
Hi @edquist, yes it is on the PR.

2023-01-23 22:47 UTC, brianhlin commented
Hey @biozit , is this ready for review? It's been a bit of a long-lived PR that seems to keep getting caches added to it and it may get a bit hairy when merging `master` back in and resolving conflicts. I'd suggest making a PR per cache (or batching a handful of caches together if they're all complete). We can help with cherry picking commits to different branches.

As for the issue with the missing site, it looks like our check is for `SITE.yaml` and is case sensitive =/.

2023-02-09 21:36 UTC, biozit commented
@brianhlin this PR is ready to review.

2023-02-10 00:13 UTC, bbockelm commented
Looks like lat/long is missing for Denver.

Please rebase with more descriptive commits (or squash if necessary)

2023-02-13 17:10 UTC, biozit commented
done

2023-02-16 21:50 UTC, brianhlin commented
@biozit did you see Brian's request here?

> Please rebase with more descriptive commits (or squash if necessary)

Looking at the history, it doesn't look like like the commits have been rebased/reworded/squashed. If you haven't worked with `git rebase` before, I like these articles https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase and https://www.atlassian.com/git/tutorials/merging-vs-rebasing.

As for for rewording or squashing the commits themselves, I'd read through https://osg-htc.org/technology/software/git-software-development/#making-good-pull-requests-the-art-of-good-commits

2023-02-17 03:17 UTC, biozit commented
Let me create a new PR; this one is too fuzzy

2023-02-17 03:17 UTC, closed without merging