Removing downtime
opensciencegrid/topology pull request #3626
Opened 2024-02-07 21:21 UTC by biozit

The cache is back

2024-02-07 21:22 UTC, matyasselmeci approved these changes

2024-02-07 21:23 UTC, matyasselmeci requested changes
Can you either delete the downtime file or put the downtime entry back and just change the EndTime?

2024-02-09 18:12 UTC, biozit commented
> Can you either delete the downtime file or put the downtime entry back and just change the EndTime?
sure, done.

2024-02-09 18:43 UTC, matyasselmeci approved these changes

2024-02-09 18:43 UTC, merged